SELECT TOP 1* FROM DIM_LOCATION
SELECT TOP 1* FROM DIM_CUSTOMER
SELECT TOP 1* FROM DIM_DATE
SELECT TOP 1* FROM DIM_MANUFACTURER
SELECT TOP 1* FROM DIM_MODEL
SELECT TOP 1* FROM FACT_TRANSACTIONS

--1. LIST ALL THE STATES IN WHICH WE HAVE CUSTOMERS WHO HAVE BOUGHT CELLPHONES 
--   FROM 2005 TILL TODAY. 
SELECT B.IDLOCATION , B.STATE FROM FACT_TRANSACTIONS AS A 
LEFT JOIN  DIM_LOCATION AS B
ON A.IDLOCATION = B.IDLOCATION
WHERE A.DATE BETWEEN '01-01-2005' AND GETDATE()


--2. WHAT STATE IN THE US IS BUYING THE MOST 'SAMSUNG' CELL PHONES? 
SELECT TOP 1 B.IDLOCATION , B.STATE, SUM(A.QUANTITY) AS QUATITY_BROUGHT FROM FACT_TRANSACTIONS AS A 
LEFT JOIN  DIM_LOCATION AS B
ON A.IDLOCATION = B.IDLOCATION
LEFT JOIN DIM_MODEL AS C
ON A.IDMODEL = C.IDMODEL
LEFT JOIN DIM_MANUFACTURER AS D
ON C.IDMANUFACTURER = D.IDMANUFACTURER
WHERE B.COUNTRY = 'US' AND D.MANUFACTURER_NAME = 'SAMSUNG'
GROUP BY B.IDLOCATION , B.STATE
ORDER BY QUATITY_BROUGHT DESC

--3. SHOW THE NUMBER OF TRANSACTIONS FOR EACH MODEL PER ZIP CODE PER STATE. 
SELECT B.MODEL_NAME,C.ZIPCODE,C.STATE, COUNT(*) AS COUNT_TRANSACTIONS 
FROM FACT_TRANSACTIONS AS A
LEFT JOIN DIM_MODEL AS B
ON A.IDMODEL = B.IDMODEL
LEFT JOIN DIM_LOCATION AS C
ON A.IDLOCATION = C.IDLOCATION
GROUP BY B.MODEL_NAME,C.ZIPCODE,C.STATE
ORDER BY COUNT_TRANSACTIONS DESC

--4. SHOW THE CHEAPEST CELLPHONE (OUTPUT SHOULD CONTAIN THE PRICE ALSO)

SELECT TOP 1 B.MANUFACTURER_NAME, A.IDMODEL,A.MODEL_NAME, A.UNIT_PRICE FROM DIM_MODEL AS A
INNER JOIN DIM_MANUFACTURER AS B
ON A.IDMANUFACTURER = B.IDMANUFACTURER
ORDER BY A.UNIT_PRICE

--5. FIND OUT THE AVERAGE PRICE FOR EACH MODEL IN THE TOP5 MANUFACTURERS IN 
--   TERMS OF SALES QUANTITY AND ORDER BY AVERAGE PRICE. 
SELECT D.IDMODEL,D.MODEL_NAME,AVG(D.UNIT_PRICE) AS AVG_PRICE
FROM DIM_MODEL AS D
WHERE D.IDMANUFACTURER IN (
                          SELECT TOP 5 B.IDMANUFACTURER   FROM FACT_TRANSACTIONS AS A
                          LEFT JOIN DIM_MODEL AS B 
                          ON A.IDMODEL = B.IDMODEL
                          LEFT JOIN DIM_MANUFACTURER AS C
                          ON B.IDMANUFACTURER = C.IDMANUFACTURER
                          GROUP BY B.IDMANUFACTURER, C.MANUFACTURER_NAME
                          ORDER BY SUM(A.QUANTITY) DESC 
                           )
GROUP BY D.IDMODEL,D.MODEL_NAME
ORDER BY AVG_PRICE DESC

--6. LIST THE NAMES OF THE CUSTOMERS AND THE AVERAGE AMOUNT SPENT IN 2009, 
--   WHERE THE AVERAGE IS HIGHER THAN 500 

SELECT B.IDCUSTOMER, B.CUSTOMER_NAME, AVG(A.QUANTITY*A.TOTALPRICE) AS AVG_AMOUNT
FROM FACT_TRANSACTIONS AS A
LEFT JOIN DIM_CUSTOMER AS B
ON A.IDCUSTOMER = B.IDCUSTOMER
WHERE YEAR(A.DATE) = 2009
GROUP BY B.IDCUSTOMER, B.CUSTOMER_NAME
HAVING AVG(A.QUANTITY*A.TOTALPRICE)>500
ORDER BY AVG_AMOUNT DESC

--7. LIST IF THERE IS ANY MODEL THAT WAS IN THE TOP 5 IN TERMS OF QUANTITY, 
--   SIMULTANEOUSLY IN 2008, 2009 AND 2010 

SELECT TOP 5 B.MODEL_NAME ,SUM(A.QUANTITY) AS QUANTITY_ FROM FACT_TRANSACTIONS AS A 
LEFT JOIN DIM_MODEL AS B 
ON A.IDMODEL = B.IDMODEL
WHERE YEAR(A.DATE) = 2008
GROUP BY B.MODEL_NAME
ORDER BY QUANTITY_ DESC 

SELECT TOP 5 B.MODEL_NAME ,SUM(A.QUANTITY) AS QUANTITY_ FROM FACT_TRANSACTIONS AS A 
LEFT JOIN DIM_MODEL AS B 
ON A.IDMODEL = B.IDMODEL
WHERE YEAR(A.DATE) = 2009
GROUP BY B.MODEL_NAME
ORDER BY QUANTITY_ DESC 

SELECT TOP 5 B.MODEL_NAME ,SUM(A.QUANTITY) AS QUANTITY_ FROM 
FACT_TRANSACTIONS AS A 
LEFT JOIN DIM_MODEL AS B 
ON A.IDMODEL = B.IDMODEL
WHERE YEAR(A.DATE) = 2010
GROUP BY B.MODEL_NAME
ORDER BY QUANTITY_ DESC 

--8. SHOW THE MANUFACTURER WITH THE 2ND TOP SALES IN THE YEAR OF 2009 AND THE 
--   MANUFACTURER WITH THE 2ND TOP SALES IN THE YEAR OF 2010. 

SELECT B.IDMANUFACTURER,C.MANUFACTURER_NAME ,SUM(A.QUANTITY*A.TOTALPRICE) AS TOTAL_SALES 
FROM FACT_TRANSACTIONS AS A
LEFT JOIN DIM_MODEL AS B 
ON A.IDMODEL = B.IDMODEL
LEFT JOIN DIM_MANUFACTURER AS C
ON B.IDMANUFACTURER = C.IDMANUFACTURER
WHERE YEAR(A.DATE)=2009
GROUP BY B.IDMANUFACTURER, C.MANUFACTURER_NAME
ORDER BY TOTAL_SALES DESC
OFFSET 1 ROW
FETCH NEXT 1 ROW ONLY

SELECT B.IDMANUFACTURER,C.MANUFACTURER_NAME ,SUM(A.QUANTITY*A.TOTALPRICE) AS TOTAL_SALES 
FROM FACT_TRANSACTIONS AS A
LEFT JOIN DIM_MODEL AS B 
ON A.IDMODEL = B.IDMODEL
LEFT JOIN DIM_MANUFACTURER AS C
ON B.IDMANUFACTURER = C.IDMANUFACTURER
WHERE YEAR(A.DATE)=2010
GROUP BY B.IDMANUFACTURER, C.MANUFACTURER_NAME
ORDER BY TOTAL_SALES DESC
OFFSET 1 ROW
FETCH NEXT 1 ROW ONLY


--9. SHOW THE MANUFACTURERS THAT SOLD CELLPHONES IN 2010 BUT DID NOT IN 2009. 

SELECT C.IDMANUFACTURER , C.MANUFACTURER_NAME  FROM FACT_TRANSACTIONS AS A
LEFT JOIN DIM_MODEL AS B
ON A.IDMODEL = B.IDMODEL
LEFT JOIN DIM_MANUFACTURER AS C
ON B.IDMANUFACTURER = C.IDMANUFACTURER
WHERE YEAR(A.DATE) = 2010
EXCEPT
SELECT C.IDMANUFACTURER , C.MANUFACTURER_NAME  FROM FACT_TRANSACTIONS AS A
LEFT JOIN DIM_MODEL AS B
ON A.IDMODEL = B.IDMODEL
LEFT JOIN DIM_MANUFACTURER AS C
ON B.IDMANUFACTURER = C.IDMANUFACTURER
WHERE YEAR(A.DATE) = 2009

--10. FIND TOP 100 CUSTOMERS AND THEIR AVERAGE SPEND, AVERAGE QUANTITY BY EACH 
--    YEAR
SELECT  T.YEAR_,T.CUSTOMER_NAME,T.AVG_SPEND,T.AVG_QUANTITY FROM (
      SELECT  YEAR(A.DATE) AS YEAR_,B.CUSTOMER_NAME ,AVG(A.QUANTITY) AS AVG_QUANTITY, 
      AVG(A.QUANTITY*A.TOTALPRICE) AS AVG_SPEND,
      DENSE_RANK () OVER (PARTITION BY YEAR(A.DATE) ORDER BY AVG(A.QUANTITY)DESC, AVG(A.QUANTITY*A.TOTALPRICE) DESC) AS RANK_
      FROM FACT_TRANSACTIONS AS A 
      LEFT JOIN DIM_CUSTOMER AS B
      ON A.IDCUSTOMER = B.IDCUSTOMER
      GROUP BY YEAR(A.DATE),B.CUSTOMER_NAME
       ) AS T
WHERE T.RANK_ <=100
ORDER BY T.YEAR_,AVG_SPEND DESC,T.AVG_QUANTITY DESC

------------------------------XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX----------------------------------------

SELECT TOP 1* FROM DIM_LOCATION
SELECT TOP 1* FROM DIM_CUSTOMER
SELECT TOP 1* FROM DIM_DATE
SELECT TOP 1* FROM DIM_MANUFACTURER
SELECT TOP 1* FROM DIM_MODEL
SELECT TOP 1* FROM FACT_TRANSACTIONS